# This default compose env allow you to interact locally with PostgreSQL
version: '1'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DBNAME:-postgres}
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: ${POSTGRES_DBNAME:-postgres}
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    volumes:
      - .:/app

volumes:
  pg_data:
    name: bball_pgdata
