name: Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, ready_for_review, edited]
  workflow_dispatch:
  pull_request_target:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: setup.cfg
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('**/setup.cfg') }}-test
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            pip install -e .[all]
            pip install flake8 pytest
      - name: Lint
        run: bash scripts/lint.sh
      - name: Test
        run: pytest -v
      # - name: Test
      #   run: bash scripts/tests.sh
      #   env:
      #     COVERAGE_FILE: coverage/.coverage.${{ runner.os }}-py${{ matrix.python-version }}
      #     CONTEXT: ${{ runner.os }}-py${{ matrix.python-version }}
      # - name: Store coverage files
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: coverage
      #     path: coverage